version: '3.9'

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: find-difference-nginx
        ports:
            - "3417:80"
        volumes:
            - ./:/var/www/project
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php82-service
            - mariadb

    # php
    php82-service:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: find-difference-php
        ports:
            - "1217:9000"
        volumes:
            - ./:/var/www/project
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini

    # mysql
    mariadb:
        image: mariadb
        container_name: find-difference-mariadb
        ports:
            - "1206:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
            - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        #restart: always
        environment:
            #MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
            #MYSQL_PASSWORD: root